//import React from 'react'
import './textToSpeech.css'
export default function TextToSpeech() {
    return (
        <div className="text-to-speech">
            <h2 className="text-to-speech-title">Text2Speech</h2>
            <p>April 2024 - May 2024</p>
            <p>Independent Project</p>

            <section className="project-section">
                <h4>Dynamic Cloud-Native Web Application</h4>

                <p>Embarked on the creation of a cutting-edge cloud-native web app, leveraging Amazon S3, AWS Lambda, and API Gateway to empower users with seamless text-to-voice conversion. Through meticulous design and implementation, crafted an immersive experience where users can interact with lifelike voices generated by AWS Polly in real-time.</p>

                <h3>Key Accomplishments</h3>
                <ul>
                    <li>Strategically designed and implemented a cloud-native architecture utilizing serverless services like AWS Lambda, API Gateway, and S3, showcasing expertise in scalable and cost-efficient solutions.</li>
                    <li>Employed a serverless approach to minimize infrastructure management overhead, allowing for automatic scaling and optimal resource utilization based on demand.</li>
                    <li>Optimized performance and reliability by leveraging AWS Polly for text-to-voice conversion, ensuring a seamless and responsive user experience.</li>
                    <li>Implemented fault-tolerant design patterns to ensure system resilience and minimize downtime, enhancing the overall reliability of the application.</li>
                    <li>Demonstrated proficiency in cloud-native development principles, enabling rapid iteration and deployment of new features while maintaining high levels of availability and performance.</li>
                </ul>

                
            </section>
            <section className="project-section">
                {/* <h3>GitHub Repository</h3>
                <p><a href="https://github.com/your-text2speech-repo-url" target="_blank" rel="noopener noreferrer">GitHub Repository</a></p> */}

                <h3>Visit Text2Speech</h3>
                <p><a href="http://text-speech-web.s3-website.ca-central-1.amazonaws.com/" target="_blank" rel="noopener noreferrer">Text2Speech</a></p>
            </section>
        </div>
    )
}
